### ISSUE TITLE
Custom Field Type Name 'sales_invoices' is wrong.

### ISSUE THREAD

**Issue by mikevmil** [VincentVrijburg/moneybird-dotnet#104]
In contrary to what the documentation says on https://developer.moneybird.com/api/custom_fields/#get_custom_fields, the sales_invoices type does not exist. It should be sales_invoice. This breaks the serialization when trying to use the GetCustomFields endpoint. Could this be changed?

**Comment by VincentVrijburg** [comment]
I see the discrepancy in the documentation now. Thanks for reporting!

The bugfix is part of the #105 pull request and is being pushed to NuGet. You can expect it to be available for download in the next few minutes.
